services:
  - type: web
    name: weather-backend
    env: node
    rootDir: weather/backend
    buildCommand: yarn install
    startCommand: yarn start
    plan: free

  - type: web
    name: weather-frontend
    env: node
    rootDir: weather/my-app
    buildCommand: yarn install && yarn build
    startCommand: npx serve -s build
    plan: free
